#ifndef CONFIGURATION_H
#define CONFIGURATION_H

#define RESULT_FOLDER "./results/"

#define IN_IMAGES_FOLDER RESULT_FOLDER "pgm/"

#define DATA_FOLDER RESULT_FOLDER "data/"

#define CROPPED_IMAGE_FOLDER RESULT_FOLDER "cropped/"

#define SEED_IMAGE_FOLDER RESULT_FOLDER "seed/"

#define SOLUTION_IMAGE_FOLDER RESULT_FOLDER "solution/"

#define FINAL_SOLUTION_IMAGE_FOLDER RESULT_FOLDER "final_solution/"

#define FILENAME_LENGTH 40

#endif //CONFIGURATION_H